
while deploying, use beow contents

spring.application.name=pandaNow
server.port=4000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.thymeleaf.cache=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=utf-8




#
#spring.application.name=pandaNow
#
#
#
#server.port=4000
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/pandanow
#spring.datasource.username=postgres
#spring.datasource.password=3000
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
#
#
#spring.thymeleaf.cache=false
#
#spring.messages.basename=messages
#spring.messages.encoding=UTF-8
#spring.session.store-type=none
#
#
#
#
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.encoding=utf-8